### PR TITLE
Improve addNode step of onboarding & fix MagicLink redux state

### LINKED ISSUE #436: Fix Magic Link and improve Add Node step
Definition of done
- Magic link seems to have stopped working, probably the state is reset somewhere
- If you type your owner address in the 'Add Node' setep in Onboarding, the TextField should become red (error props) and have a helperText 'Your node address can't be the ownser address'

### PR DESCRIPTION
**Pull request by ItsLuized**
Fixes #436 #401

## Overview
- Add check to show error if address inputted in add node is same as ownerAddress
- Fix magicLink state on redux getting reset.

### CODE REVIEW

File: src/pages/staking-hub/onboarding/step5/0addNode.tsx [hunk 1]
```diff
@@ -70,10 +71,18 @@ export default function AddNode() {
...
     }
   };
 
+
+  const addressIsOwnerAddress = () => {
+    if (ownerAddress === address) {
+      return true
+    }
+    return false
+  }
```
Comment (mjadach-iv) [inline src/pages/staking-hub/onboarding/step5/0addNode.tsx:84]: Sometimes the addresses can have different size of cases

```suggestion
   return ownerAddress?.toLocaleLowerCase() === address?.toLocaleLowerCase()
```

**Review by mjadach-iv — CHANGES_REQUESTED** [review]

**Review by mjadach-iv — APPROVED** [review]
